---
- name: Subscription Register !
  hosts: all
 
  tasks:
 
  - name: Register Subscription 
    redhat_subscription:
      state=present
      username={{ RHSM_USERNAME }}
      password={{ RHSM_PASSWORD }}
      pool='^Employee SKU$'
